name = "chipmunk2d"
description = "Ada bindings for Chipmunk2D"
version = "0.2.0-dev"

authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <fabien.chouteau@gmail.com>"]
maintainers-logins = ["Fabien-Chouteau"]
licenses = "MIT"
website = ""
tags = ["gamedev", "binding"]

[[depends-on]]
libchipmunk = "^7.0.3"
